# Generated by Django 2.1.5 on 2019-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_numb_option',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
