# Generated by Django 2.1.5 on 2019-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_question_quest_numb_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_numb_option',
            field=models.IntegerField(default=1),
        ),
    ]
