# Generated by Django 2.1.5 on 2019-03-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190311_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_option',
            field=models.CharField(default='notspecified', max_length=100),
        ),
    ]
