# Generated by Django 2.1.5 on 2019-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190311_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.CharField(default='custom', max_length=50),
        ),
    ]
