# Generated by Django 2.1.5 on 2019-03-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0006_form_form_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-form_posted']},
        ),
        migrations.AddField(
            model_name='response_user_list',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Form'),
        ),
        migrations.AddField(
            model_name='response_user_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
