# Generated by Django 2.1.5 on 2019-04-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='form_link',
        ),
    ]
