# Generated by Django 2.1.5 on 2019-04-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_form_form_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='form_type',
        ),
    ]
